openapi: 3.0.3
info:
  title: STD24206
  description: This is a specification of STD24206
  version: 1.0.0
servers:
  - url: "http://localhost:8000"
paths:
  /ping:
    get:
      responses:
        '200':
          description: get Pong
          content:
            text/plain:
              schema:
                type: string
                example: pong




