openapi: 3.0.3
info:
  title: STD24206
  description: This is a specification of STD24206
  version: 1.0.0
servers:
  - url: "http://localhost:8000"
paths:
  /cars:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/cars/type"
      responses:
        201:
          description: Car created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/cars/type"
      components:
        cars:
        type: object
        properties:
          - id:
              type: integer
          - brand:
              type: string
          - model:
              type: string
          - characteristic:
              type: object
              items:
                properties:
                  - max_speed:
                      type: number
                  - max_fuel_capacity:
                      type: number






  
